services:
  mongo:
    image: mongo
    container_name: notext-mongo
    restart: always
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    container_name: notext-api
    restart: always
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/notext
      - JWT_SECRET=titkos_kulcs
    depends_on:
      - mongo
    volumes:
      - ./data/uploads:/app/uploads
  frontend:
    build: ./frontend
    container_name: notext-client
    restart: always
  nginx:
    image: nginx:alpine
    container_name: notext-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend